### ISSUE TITLE
Router alpha 3 seems to be not working with webpack\ts-loader\typescript 1.8.10

### ISSUE THREAD

**Issue by kamarouski** [angular/vladivostok#46]
Trying to use the new router in my project and get a lot of issues related to *.d.ts files while building the app with webpack and ts-loader.

Some of the errors are below:

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(4,14): error TS1005: '=' expected.

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(4,18): error TS1005: ';' expected.

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(5,23): error TS1110: Type expected.

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(7,27): error TS1110: Type expected.

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(5,23): error TS2300: Duplicate identifier 'null'.

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(7,27): error TS2300: Duplicate identifier 'null'.

ERROR in C:\repo\node_modules\@angular\router\utils\tree.d.ts
(4,14): error TS2304: Cannot find name 'root'.

ERROR in C:\repo\node_modules\@angular\router\url_tree.d.ts
(7,24): error TS1110: Type expected.

ERROR in C:\repo\node_modules\@angular\router\url_tree.d.ts
(10,27): error TS1110: Type expected.

ERROR in C:\repo\node_modules\@angular\router\url_tree.d.ts
(10,8): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in C:\repo\node_modules\@angular\router\router_state.d.ts
(29,27): error TS1110: Type expected.

**Comment by kamarouski** [comment]
Solved issue. It appears to be the new router uses dev version of typescript (1.9.0-dev.20160409). After typescript update errors dissapeared.

**Comment by ericmartinezr** [comment]
see https://github.com/angular/vladivostok/issues/39

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/vladivostok/commit/157b8cd5b3c15668eeb7643a0ed8e0b5cb90e67a
